{% set name = "standardebooks" %}
{% set version = "2.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/standardebooks-{{ version }}.tar.gz
  sha256: 5b4a06d9f48272ca192588084fc32c631f7e25eb6022b87f1155966f12410759

build:
  number: 0
  noarch: python
  entry_points:
    - se = se.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools ==70.0.0
  run:
    - python >=3.10
    - cairosvg ==2.7.1
    - chardet ==5.2.0
    - cssselect ==1.2.0
    - cssutils ==2.9.0
    - ftfy >=6.0.3
    - gitpython ==3.1.41
    - importlib_resources
    - lxml ==4.9.3
    - natsort ==8.4.0
    - pillow ==10.3.0
    - psutil ==5.9.6
    - pyphen ==0.14.0
    - regex ==2023.10.3
    - requests >=2.32.0
    - rich ==13.7.0
    - roman ==4.1
    - selenium ==4.9.0
    - smartypants ==2.0.1
    - setuptools ==70.0.0
    - tinycss2 ==1.2.1
    - titlecase ==2.4
    - unidecode ==1.3.7

test:
  imports:
    - se
  commands:
    # Upstream pin too stringent disabling pip check here
    # - pip check
    - se --help
  requires:
    - pip

about:
  home: https://standardebooks.org
  summary: The toolset used to produce Standard Ebooks epub ebooks.
  dev_url: https://github.com/standardebooks/tools/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  description: |
    A collection of tools Standard Ebooks uses to produce its ebooks,
     including basic setup of ebooks, text processing, and build tools.
    Installing this toolset using pipx or conda makes the se command
     line executable available. Its various commands are described below,
     or you can use se help to list them.

extra:
  recipe-maintainers:
    - thewchan
