{% set name = "standardebooks" %}
{% set version = "2.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/standardebooks-{{ version }}.tar.gz
  sha256: 15ffbe25fae4a4e6048095a9e13ee8f28d9548a4fb87afccbf387f69251199db

build:
  number: 0
  noarch: python
  entry_points:
    - se = se.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cairosvg ==2.5.2
    - chardet ==4.0.0
    - cssselect ==1.1.0
    - cssutils ==2.3.0
    - ftfy ==6.0.3
    - gitpython ==3.1.11
    - importlib_resources ==1.0.2
    - lxml ==4.6.3
    - natsort ==7.1.1
    - pillow ==8.3.2
    - psutil ==5.8.0
    - pyopenssl ==20.0.0
    - pyphen ==0.11.0
    - python >=3.6
    - regex ==2021.08.28
    - requests ==2.26.0
    - rich ==10.9.0
    - roman ==3.3.0
    - selenium ==3.141.0
    - smartypants ==2.0.1
    - tinycss2 ==1.1.0
    - titlecase ==2.3
    - unidecode ==1.2.0

test:
  imports:
    - se
    - se.commands
  commands:
    - se --help
    - pip list | grep -E '{{ name }}\s+{{ version }}'
  requires:
    - pip

about:
  home: https://standardebooks.org
  summary: The toolset used to produce Standard Ebooks epub ebooks.
  dev_url: https://github.com/standardebooks/tools/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  description: |
    A collection of tools Standard Ebooks uses to produce its ebooks,
     including basic setup of ebooks, text processing, and build tools.
    Installing this toolset using pipx or conda makes the se command
     line executable available. Its various commands are described below,
     or you can use se help to list them.

extra:
  recipe-maintainers:
    - thewchan
