{% set name = "standardebooks" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/standardebooks-{{ version }}.tar.gz
  sha256: 09c8bac117ca5ad1db589ef3aff6beb2770873566dfe913e85bc5603e69143c3

build:
  number: 0
  noarch: python
  entry_points:
    - se = se.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cairosvg ==2.7.0
    - chardet ==5.1.0
    - cssselect ==1.2.0
    - cssutils ==2.6.0
    - ftfy ==6.0.3
    - gitpython ==3.1.30
    - importlib_resources ==1.0.2
    - lxml ==4.9.2
    - natsort ==8.3.1
    - pillow ==9.5.0
    - psutil ==5.9.4
    - pyphen ==0.14.0
    - python >=3.7
    - regex ==2022.10.31
    - requests ==2.31.0
    - rich ==13.3.5
    - roman ==4.0
    - selenium ==4.9.0
    - smartypants ==2.0.1
    - tinycss2 ==1.2.1
    - titlecase ==2.4
    - unidecode ==1.3.6

test:
  imports:
    - se
  commands:
    - pip check
    - se --help
  requires:
    - pip

about:
  home: https://standardebooks.org
  summary: The toolset used to produce Standard Ebooks epub ebooks.
  dev_url: https://github.com/standardebooks/tools/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  description: |
    A collection of tools Standard Ebooks uses to produce its ebooks,
     including basic setup of ebooks, text processing, and build tools.
    Installing this toolset using pipx or conda makes the se command
     line executable available. Its various commands are described below,
     or you can use se help to list them.

extra:
  recipe-maintainers:
    - thewchan
