{% set name = "standardebooks" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/standardebooks-{{ version }}.tar.gz
  sha256: f819c0eb752ea6f580bfaf66b5ced3235c9c91bc1d7a7dc5a34f4229524ac421

build:
  number: 0
  noarch: python
  entry_points:
    - se = se.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cairosvg ==2.5.2
    - chardet ==3.0.4
    - cssselect ==1.1.0
    - cssutils ==1.0.2
    - ftfy ==5.8
    - gitpython ==3.1.11
    - importlib_resources ==1.0.2
    - lxml ==4.6.3
    - natsort ==7.1.0
    - pillow ==8.1.1
    - psutil ==5.8.0
    - pyopenssl ==20.0.0
    - pyphen ==0.10.0
    - python >=3.6
    - regex ==2020.11.13
    - requests ==2.25.0
    - rich ==9.4.0
    - roman ==3.3.0
    - selenium ==3.141.0
    - smartypants ==2.0.1
    - tinycss2 ==1.1.0
    - titlecase ==0.13.0
    - unidecode ==1.2.0

test:
  imports:
    - se
    - se.commands
  commands:
    - pip check
    - se --help
  requires:
    - pip

about:
  home: https://standardebooks.org
  summary: The toolset used to produce Standard Ebooks epub ebooks.
  dev_url: https://github.com/standardebooks/tools/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  description: |
    A collection of tools Standard Ebooks uses to produce its ebooks,
     including basic setup of ebooks, text processing, and build tools.
    Installing this toolset using pipx or conda makes the se command
     line executable available. Its various commands are described below,
     or you can use se help to list them.

extra:
  recipe-maintainers:
    - thewchan
