{% set name = "standardebooks" %}
{% set version = "2.7.5" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/standardebooks-{{ version }}.tar.gz
  sha256: ad87225db87b6c074f2855bc95d669d3002aaa67c1e26f01f1a99968b3bb9144

build:
  number: 0
  noarch: python
  entry_points:
    - se = se.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools ==78.1.0
  run:
    - python >={{ python_min }}
    - cairosvg ==2.7.1
    - chardet ==5.2.0
    - cssselect ==1.3.0
    - cssutils ==2.11.1
    - ftfy ==6.3.1
    - gitpython ==3.1.44
    - importlib_resources ==1.0.2
    - lxml ==5.3.2
    - natsort ==8.4.0
    - pillow ==11.2.1
    - psutil ==7.0.0
    - pyphen ==0.17.2
    - regex >=2024.11.6
    - requests ==2.32.3
    - rich ==14.0.0
    - roman ==5.0
    - selenium >=4.31.0
    - setuptools ==78.1.0
    - smartypants ==2.0.1
    - tinycss2 ==1.4.0
    - titlecase ==2.4.1
    - unidecode ==1.3.8

test:
  imports:
    - se
  commands:
    # Upstream pin too stringent disabling pip check here
    # - pip check
    - se --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://standardebooks.org
  summary: The toolset used to produce Standard Ebooks epub ebooks.
  dev_url: https://github.com/standardebooks/tools/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  description: |
    A collection of tools Standard Ebooks uses to produce its ebooks,
     including basic setup of ebooks, text processing, and build tools.
    Installing this toolset using pipx or conda makes the se command
     line executable available. Its various commands are described below,
     or you can use se help to list them.

extra:
  recipe-maintainers:
    - thewchan
