schema_version: 1

context:
  name: standardebooks
  version: "3.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/standardebooks-${{ version }}.tar.gz
  sha256: 754fd4c2c9850d264c2ffeae3b7e9af9a984e750d40a460384431b2dc522ba03

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - se = se.main:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools ==80.9.0
  run:
    - python >=${{ python_min }}
    - cairosvg ==2.8.2
    - chardet ==5.2.0
    - cssselect ==1.4.0
    - cssutils ==2.11.1
    - ftfy ==6.3.1
    - gitpython ==3.1.46
    - importlib_resources >=1.0.2
    - lxml ==6.0.2
    - natsort ==8.4.0
    - pillow ==12.1.1
    - psutil ==7.2.2
    - pyoxipng ==9.1.1
    - pyphen ==0.17.2
    - regex ==2026.2.28
    - repro-zipfile ==0.4.1
    - requests ==2.32.5
    - rich ==14.3.3
    - roman ==5.2
    - selenium ==4.41.0
    - setuptools ==80.9.0
    - smartypants ==2.0.2
    - tinycss2 ==1.5.1
    - titlecase ==2.4.1
    - unidecode ==1.4.0

tests:
  - python:
      imports:
        - se
      # Selanium and regex pin too tight, use more relased pins and skip pip check
      pip_check: false
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - se --help

about:
  summary: The toolset used to produce Standard Ebooks epub ebooks.
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  description: |
    A collection of tools Standard Ebooks uses to produce its ebooks,
    including basic setup of ebooks, text processing, and build tools.
    Installing this toolset using pipx or conda makes the se command
    line executable available. Its various commands are described below,
    or you can use se help to list them.


  homepage: https://standardebooks.org
  repository: https://github.com/standardebooks/tools/

extra:
  recipe-maintainers:
    - thewchan
