schema_version: 1

context:
  name: standardebooks
  version: "2.9.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/standardebooks-${{ version }}.tar.gz
  sha256: cca868cc7755a74b3058079df16d56471ba75b55154b06dd5b1b09e903d36391

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - se = se.main:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools ==78.1.1
  run:
    - python >=${{ python_min }}
    - cairosvg ==2.7.1
    - chardet ==5.2.0
    - cssselect ==1.3.0
    - cssutils ==2.11.1
    - ftfy ==6.3.1
    - gitpython ==3.1.44
    - importlib_resources >=1.0.2
    - lxml ==5.3.2
    - natsort ==8.4.0
    - pillow ==11.3.0
    - psutil ==7.0.0
    - pyphen ==0.17.2
    - regex >=2024.11.6
    - repro_zipfile ==0.4.0
    - requests ==2.32.4
    - rich ==14.0.0
    - roman ==5.0
    - selenium >=4.31.0
    - setuptools ==78.1.1
    - smartypants ==2.0.2
    - tinycss2 ==1.4.0
    - titlecase ==2.4.1
    - unidecode ==1.3.8

tests:
  - python:
      imports:
        - se
      # Selanium and regex pin too tight, use more relased pins and skip pip check
      pip_check: false
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - se --help

about:
  summary: The toolset used to produce Standard Ebooks epub ebooks.
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  description: |
    A collection of tools Standard Ebooks uses to produce its ebooks,
    including basic setup of ebooks, text processing, and build tools.
    Installing this toolset using pipx or conda makes the se command
    line executable available. Its various commands are described below,
    or you can use se help to list them.


  homepage: https://standardebooks.org
  repository: https://github.com/standardebooks/tools/

extra:
  recipe-maintainers:
    - thewchan
